---
- name: Build container contrail-test-test OpenStack-{{ item }}
  command: |
    ./build-container.sh test \
    --base-tag {{ contrail_container_tag }} \
    --tag {{ item }}-{{ contrail_container_tag }} \
    --registry-server {{ contrail_docker_registry }} \
    --sku {{ item }} \
    --contrail-repo {{ contrail_package_repository }} \
    --openstack-repo http://ci-repo.englab.juniper.net/mirrors/rpm/centos/7.4.1708/cloud/x86_64/openstack-{{ item }} \
    --post
  args:
    chdir: "{{ test_container_build_dir }}"
  become: true

