---
- hosts: all
  roles:
    - acquire-ip-address
    - self-ssh-key
    - prepare-template-for-ansible-deployer
    - contrail-ansible-deployer

- hosts: all
  tasks:
    - fail:
        msg: 'fail'
