---
container_name:
    - contrail-windows-cnm-plugin
    - contrail-windows-docker-driver
    - contrail-windows-vrouter
workdir: '{{ zuul.projects | selectattr("short_name", "equalto", "containerregistry") | map(attribute="src_dir") | list | first }}'
