---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yaml"

- name: create package dir on the executor
  file:
    path: "{{ zuul.executor.work_root }}/packages"
    state: directory
  delegate_to: localhost

- name: get a list of packages
  find:
    paths: "{{ ansible_env.HOME }}/"
    patterns: "{{ package_pattern }}"
    recurse: true
  register: packages

- name: Fetch packages from the build VM to the executor
  synchronize:
    src: "{{ item.path }}"
    dest: "{{ zuul.executor.work_root }}/packages/{{ item.path|basename }}"
    mode: pull
  with_items: "{{ packages.files }}"

