---

# support for multinode deployments
# * If deployment node exists:
#   - generates an ssh key for the deployment user on the deployment node
#   - distributes the public part of the key to allow access on all nodeset nodes
#   - install docker on it
#   - add the insecure docker registry to it
# * Inserts dns entries about all nodeset nodes in /etc/hosts on all nodeset nodes

# Support for AIO deployments
# contrail-ansible-deployer docker in a different version / from a different repo than in c-z-j
# TODO: work this out, so installation methods are in sync

- hosts: all
  roles:
    - yum-repos-prepare
    - install-pip-virtualenv
    - install-ntp

- hosts: deployment:!control-plane:!data-plane
  roles:
    - install-docker-daemon
    - role: add-insecure-registry
      new_registry: "{{ contrail_docker_registry }}"

- hosts: deployment
  roles:
    - self-ssh-key
    - install-ansible

- hosts: all
  tasks:
    - name: ensure the deployment user's ssh key is present in authorized_keys on all nodes
      become: true
      authorized_key:
        user: "{{ hostvars[groups['deployment'][0]].user.name }}"
        key: "{{ hostvars[groups['deployment'][0]].pubkey.stdout }}"
      when: "'deployment' in groups"

- hosts: all
  vars:
    query: '*.{address: ansible_default_ipv4.address, fqdn: ansible_fqdn}'
  roles:
    - role: configure-hosts-entries
      hosts_entries: '{{ hostvars | json_query(query) }}'

