- hosts: all
  roles:
    - acquire-ip-address
    - contrail-helm-deployer
    - role: add-insecure-registry
      new_registry: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}"
    - role: self-ssh-key
      user: root
    - sanitytest
      openstack_version: ocata
