---
- name: Load variables needed for docker deamon installation based on the OS type
  include_vars: "{{ ansible_os_family | lower }}.yaml"

- name: Ensure that docker python bindings are installed
  package:
    name: "{{ docker_py_pkg }}"
    state: present
  become: true

- name: Push container images to the repository
  publish_images:
    images: "{{ images }}"
    tag: "{{ tag }}"
    registry: "{{ registry }}"
  become: true

