---
- name: Acquire IP address for interfaces that miss it
  command: "dhclient {{ item }}"
  with_items:
    - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"
  when:
    - hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
    - not 'ipv4' in hostvars[inventory_hostname]['ansible_' + item]
  become: true

- name: Reload ansible facts
  setup:

