---

- name: create directory hierarchy for xmls
  file:
    path: '{{ results_dir }}/{{ item.xml_path | dirname }}'
    state: 'directory'
    owner: 'zuul'
    mode: 0755
  with_items: '{{ matched_targets }}'

- name: find the tests report xml file
  find:
    paths: '{{ packaging.target_dir }}/{{ (item.xml_path | dirname).split("xmls")[1] }}'
    pattern: "{{ item.xml_path.split('.xml')[0] | basename }}.*.xml"
    file_type: file
  become: true
  register: xml_report_file
  with_items: '{{ matched_targets }}'

- name: gzip reports
  archive:
    path: '{{ item.1.path }}'
    remove: false
  become: true
  with_subelements:
    - '{{ xml_report_file.results }}'
    - 'files'
  when: xml_report_file.results | length > 0

- name: copy gziped xml reports
  copy:
    src: '{{ item.1.path }}.gz'
    dest: '{{ results_dir }}/{{ item.0.item.xml_path | dirname }}/'
    remote_src: true
    owner: 'zuul'
    mode: 0644
  with_subelements:
    - '{{ xml_report_file.results }}'
    - 'files'
  when: xml_report_file.results | length > 0

