---
- name: set facts
  vars:
    src_dir: '{{ zuul.projects | selectattr("short_name", "equalto", "contrail-test") | map(attribute="src_dir") | list | first }}'
  set_fact:
    testrunner_image: '{{ contrail_docker_registry }}/contrail-test-test:{{ openstack_version }}-{{ contrail_version }}'
    testrunner_script: '{{ ansible_env.HOME }}/{{ src_dir }}/testrunner.sh'

- name: make sure python docker bindings are installed
  become: true
  pip:
    name: 'docker-py'
    state: 'present'

- name: pull the testrunner image
  docker_image:
    name: '{{ testrunner_image }}'
  become: true

- name: (hack) change networking mode for containers run directly on docker engine
  replace:
    path: '{{ testrunner_script }}'
    regexp: '--privileged'
    replace: '--privileged --network host'
  when: (contrail_deployer is defined) and contrail_deployer == 'helm'

- name: run the sanity test
  command: |
    '{{ testrunner_script }}' run \
        -P '{{ ansible_env.HOME }}'/contrail_test_input.yaml \
        -k /root/.ssh/id_rsa \
        -f '{{ test_target }}' \
        '{{ testrunner_image }}'
  ignore_errors: yes
  become: true

- name: test the xml report for failures
  shell: "[ x\"$(grep testsuite /root/contrail-test-runs/*/reports/TESTS-TestSuites.xml  | grep -o  'failures=\\S\\+' | uniq)\" = x'failures=\"0\"' ]"
  become: true

