- name: Debug contrail_version - start sanity
  debug:
    msg: "contrail_version is {{ contrail_version }}"

- name: Set variables
  set_fact:
    testrunner_image: "{{ contrail_docker_registry }}/contrail-test-test:{{ contrail_version }}"
    repos_dir: "{{ ansible_env.HOME }}/src/{{ zuul.project.canonical_hostname }}/Juniper"

- name: Pull the testrunner image
  docker_image:
    name: "{{ testrunner_image }}"
  become: true

- name: Run the sanity test
  command: |
    "{{ repos_dir }}"/contrail-test/testrunner.sh run \
        -P "{{ ansible_env.HOME }}"/contrail_test_input.yaml \
        -k /root/.ssh/id_rsa \
        -f "{{ test_target }}" "{{ testrunner_image }}"
  become: true
  ignore_errors: yes

- name: test the xml report for failures
  shell: "[ x\"$(grep testsuite /root/contrail-test-runs/*/reports/TESTS-TestSuites.xml  | grep -o  'failures=\\S\\+' | uniq)\" = x'failures=\"0\"' ]"
  become: true

- name: Debug contrail_version - end sanity
  debug:
    msg: "contrail_version is {{ contrail_version }}"
