---
- name: os-specific tasks
  include: "{{ ansible_distribution|lower }}.yaml"

- name: Download pip installation script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: '{{ ansible_env.HOME }}/get-pip.py'
    mode: 0755
  retries: 4
  delay: 2
  register: pip_install_result
  until: pip_install_result.rc == 0

- name: Install pip
  command: 'python3 {{ ansible_env.HOME }}/get-pip.py'
  become: true

- name: install/upgrade utilities
  become: true
  command: "python3 -m pip install --upgrade {{ item }}"
  with_items:
    - pip
    - virtualenv
