---
# This role installs dependencies for building third party packages
# The process is based on mock toolchain

- name: Install dependencies for contrail-third-party-packages
  yum:
    name: '{{ item }}'
    state: 'installed'
  become: true
  with_items:
    - 'wget'
    - 'mock'
    - 'spectool'
    - 'redhat-lsb-core'
    - 'rpmdevtools'

