- hosts: all
  roles:
    - load-docker-registry-info
    - acquire-ip-address
    - self-ssh-key
    - role: contrail-ansible-deployer-new
      cloud_orchestrator: openstack
      openstack_version: ocata
      kolla_docker_distro: ubuntu
      kolla_version: ocata
    - role: sanitytest
      openstack_version: ocata
