---
- hosts: all
  roles:
    - yum-repos-prepare
    - install-pip-virtualenv
    - install-docker-daemon
    - zuul-include-vars
    - role: add-insecure-registry
      new_registry: "{{ contrail_docker_registry }}"
    - add-registry-proxy

