---
- hosts: all
  remote_user: vagrant
  become: true
  tasks:
    - name: 'update'
      apt:
        update_cache: yes

    - name: 'Looping installation of packages.'
      apt:
        name: '{{ item }}'
      with_items:
        - linux-image-extra-4.13.0-36-generic
        - linux-image-extra-virtual
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - curl
        - python-pip

    - name: 'Add Docker apt key'
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      register: add_repository_key

    - name: 'Add Docker apt key.'
      shell: 'curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
      args:
        warn: no
      when: add_repository_key|failed

    - name: 'Add docker apt repo'
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable'
        update_cache: yes

    - name: 'Install Docker apt package'
      apt:
        pkg: docker-ce

    - name: 'Ensure Docker service is installed and started'
      service:
        name: 'docker'
        state: restarted
        enabled: yes

    - name: 'docker-py install'
      pip:
        name: 'docker'

    - name: 'Create directory'
      file:
        path: /src/www
        state: directory
        mode: 0755

    - name: 'Create file'
      copy:
        content: '<body>Just a simple test</body>'
        dest: /src/www/index.html

    - name: 'Setting up docker with nginx.'
      docker_container:
        image: nginx
        name: 'test'
        state: started
        volumes:
          - /src/www:/usr/share/nginx/html:ro
        network_mode: host
