---
contrail_package_repository: "http://svl-artifactory.juniper.net/artifactory/yum-contrail-ci-build/{{ packaging.repo_names[ansible_distribution] }}/"
contrail_version: "{{ packaging.repo_name }}"
openstack_version: ''
rpm_repo_config_dir: /etc/yum.repos.d/
docker_build_dir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-container-builder"
deployers_build_dir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-deployers-containers"
ansible_deployer_dir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-ansible-deployer"
kolla_ansible_dir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-kolla-ansible"
openshift_ansible_dir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/openshift-ansible"

